--liquibase formatted sql

--changeset ShiloMY:1

/**
 * Таблица валют
 *
 * id - идентификатор
 * price - цена
 * symbol - символ валюты
 */
CREATE TABLE if NOT EXISTS currency (
    id BIGINT NOT NULL,
    price NUMERIC(19, 2),
    symbol VARCHAR(255),
    PRIMARY KEY (id)
);

/**
 * Таблица подписчиков валют
 *
 * currency_id - идентификатор валюты
 * user_id - идентификатор пользователя
 */
CREATE TABLE if NOT EXISTS currency_followers (
    currency_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

/**
 * Таблица пользователей
 *
 * id - идентификатор
 * name - имя пользователя
 */
CREATE TABLE if NOT EXISTS usr (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

/**
 * Связь пользователей с подписчиками
 */
ALTER TABLE currency_followers
ADD CONSTRAINT user_foreign_key
    FOREIGN KEY (user_id)
        REFERENCES usr;

/**
 * Связь валют с подписчиками
 */
ALTER TABLE currency_followers
ADD CONSTRAINT currency_foreign_key
    FOREIGN KEY (currency_id)
        REFERENCES currency;